/* Copyright (c) 2011-2012, Code Aurora Forum. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 and
 * only version 2 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#include <linux/kernel.h>
#include <asm/mach-types.h>
#include <linux/string.h>

#include "board-qrd7627a-gpio.h"

unsigned int * msm_gpio_table_qrd;
unsigned int * msm_lcd_gpio_table_qrd;

unsigned int msm_gpio_table_qrd_7227a_sku1[GPIO_TOTAL_NUM] =
{
	[GPIO_HOST_VBUS_EN_INDEX]		= 107, /*GPIO_HOST_VBUS_EN*/
	[GPIO_BT_SYS_REST_EN_INDEX]		= 114, /*GPIO_BT_SYS_REST_EN*/
	[GPIO_CAM_FRONT_PWDN_INDEX]		= 118, /*GPIO_CAM_FRONT_PWDN*/
	[GPIO_CAM_BACK_SHDN_EN_INDEX]	= 120, /*GPIO_CAM_BACK_SHDN_EN*/
	[GPIO_CAM_FRONT_RESET_INDEX]	= 29, /*GPIO_CAM_FRONT_RESET*/
	[GPIO_CAM_BACK_RESET_INDEX]		= 121, /*GPIO_CAM_BACK_RESET*/
	[GPIO_FM_RDS_INT_INDEX]			= 83,  /*GPIO_FM_RDS_INT*/
	[GPIO_SDC1_HW_DET_INDEX]		= 42,  /*GPIO_SDC1_HW_DET*/
	[UART1DM_RX_GPIO_INDEX]			= 45,  /*UART1DM_RX_GPIO*/
	[FT5206_IRQ_GPIO_INDEX]			= GPIO_INVALID,  /*FT5206_IRQ_GPIO*/
	[FT5206_RESET_GPIO_INDEX]		= GPIO_INVALID,  /*FT5206_RESET_GPIO*/
	[CLEARPAD3000_ATTEN_GPIO_INDEX]	= 48,  /*CLEARPAD3000_ATTEN_GPIO*/
	[CLEARPAD3000_RESET_GPIO_INDEX]	= 26,  /*CLEARPAD3000_RESET_GPIO*/
	[KYPD_DRV0_INDEX]				= 31,	/*KYPD_DRV0*/
	[KYPD_DRV1_INDEX]				= 32,	/*KYPD_DRV0*/
	[KEYSENSE_N0_INDEX]				= 36,	/*KEYSENSE_N0*/
	[KEYSENSE_N1_INDEX]				= 37,	/*KEYSENSE_N0*/
	[GPIO_COMPASS_DRDY_INDEX]		= 93,	/* COMPASS_DRDY */
	[GPIO_GYRO_INT_N_INDEX]			= 27,	/* GYRO_INT_N */
	[GPIO_ACC_INT_INDEX]			= 28,	/* ACC_INT(LIS3DH) */
	[GPIO_LTR502_INT_INDEX]			= 17,	/* LTR502_INT_GPIO */
	[LED_BLUE_INDEX]				= 12,	/*LED_BLUE*/
	[LED_RED_INDEX]					= 13,	/*LED_RED*/
	[LED_GREEN_INDEX]				= 14,	/*LED_GREEN*/
	[LED_FLASH_INDEX]				= 96,	/*LED_FLASH*/
	[GPIO_VDD33_EN_INDEX]				= 119,	/*GPIO_VDD33_EN*/
};

unsigned int msm_lcd_gpio_table_qrd_7227a_sku1[LCD_GPIO_TOTAL_NUM] =
{
	[GPIO_BACKLIGHT_EN_INDEX]		= 116, /*GPIO_BACKLIGHT_EN*/
	[GPIO_SPI_MOSI_INDEX]			= 109,  /*GPIO_SPI_MOSI*/
	[GPIO_SPI_CLK_INDEX]			= 127,  /*GPIO_SPI_CLK*/
	[GPIO_SPI_CS0_N_INDEX]			= 128,  /*GPIO_SPI_CS0_N*/
	[GPIO_DISPLAY_RESET_INDEX]		= GPIO_INVALID,    /*GPIO_DISPLAY_RESET*/
	[GPIO_DISPLAY_PWR_EN_INDEX]		= 116,  /*GPIO_DISPLAY_PWR_EN*/
	[GPIO_LCDC_BRDG_PD_INDEX]		= 128, /*	GPIO_LCDC_BRDG_PD*/
	[GPIO_LCDC_BRDG_RESET_N_INDEX]	= 129, /*GPIO_LCDC_BRDG_RESET_N*/
	[GPIO_LCD_DSI_SEL_INDEX]		= 125, /*GPIO_LCD_DSI_SEL*/
	[MDP_303_VSYNC_GPIO_INDEX]		= 97,  /*MDP_303_VSYNC_GPIO*/
	[GPIO_LCDC_PCLK_INDEX]			= 4,   /*GPIO_LCDC_PCLK*/
	[LCD_CAMERA_LDO_2V8_INDEX]		= 35,  /*LCD_CAMERA_LDO_2V8*/
	[LCD_CAMERA_LDO_1V8_INDEX]		= 40,  /*LCD_CAMERA_LDO_1V8*/
};

unsigned int msm_gpio_table_qrd_7227a_sku3[GPIO_TOTAL_NUM] =
{
	[GPIO_HOST_VBUS_EN_INDEX]		= GPIO_INVALID,  /*GPIO_HOST_VBUS_EN*/
	[GPIO_BT_SYS_REST_EN_INDEX]		= 85, /*GPIO_BT_SYS_REST_EN*/
	[GPIO_CAM_FRONT_PWDN_INDEX]		= 91, /*GPIO_CAM_FRONT_PWDN*/
	[GPIO_CAM_BACK_SHDN_EN_INDEX]	= 93, /*GPIO_CAM_BACK_SHDN_EN*/
	[GPIO_CAM_FRONT_RESET_INDEX]	= 29, /*GPIO_CAM_FRONT_RESET*/
	[GPIO_CAM_BACK_RESET_INDEX]		= 23, /*GPIO_CAM_BACK_RESET*/
	[GPIO_FM_RDS_INT_INDEX]			= 83, /*GPIO_FM_RDS_INT*/
	[GPIO_SDC1_HW_DET_INDEX]		= 42, /*GPIO_SDC1_HW_DET*/
	[UART1DM_RX_GPIO_INDEX]			= 45,  /*UART1DM_RX_GPIO*/
	[FT5206_IRQ_GPIO_INDEX]			= 48,  /*FT5206_IRQ_GPIO*/
	[FT5206_RESET_GPIO_INDEX]		= 26,  /*FT5206_RESET_GPIO*/
	[CLEARPAD3000_ATTEN_GPIO_INDEX]	= GPIO_INVALID,  /*CLEARPAD3000_ATTEN_GPIO*/
	[CLEARPAD3000_RESET_GPIO_INDEX]	= GPIO_INVALID,  /*CLEARPAD3000_RESET_GPIO*/
	[KYPD_DRV0_INDEX]				= 31,	/*KYPD_DRV0*/
	[KYPD_DRV1_INDEX]				= 32,	/*KYPD_DRV0*/
	[KEYSENSE_N0_INDEX]				= 36,	/*KEYSENSE_N0*/
	[KEYSENSE_N1_INDEX]				= 37,	/*KEYSENSE_N0*/
	[GPIO_COMPASS_DRDY_INDEX]		= 93,	/* COMPASS_DRDY */
	[GPIO_GYRO_INT_N_INDEX]			= 27,	/* GYRO_INT_N */
	[GPIO_ACC_INT_INDEX]			= 28,	/* ACC_INT(LIS3DH) */
	[GPIO_LTR502_INT_INDEX]			= 17,	/* LTR502_INT_GPIO */
	[LED_BLUE_INDEX]				= 107,	/*LED_BLUE*/
	[LED_RED_INDEX]					= 108,	/*LED_RED*/
	[LED_GREEN_INDEX]				= 109,	/*LED_GREEN*/
	[LED_FLASH_INDEX]				= 96,	/*LED_FLASH*/
};

unsigned int msm_lcd_gpio_table_qrd_7227a_sku3[LCD_GPIO_TOTAL_NUM] =
{
	[GPIO_BACKLIGHT_EN_INDEX]		= 89, /*GPIO_BACKLIGHT_EN*/
	[GPIO_SPI_MOSI_INDEX]			= 19,  /*GPIO_SPI_MOSI*/
	[GPIO_SPI_CLK_INDEX]			= 20,  /*GPIO_SPI_CLK*/
	[GPIO_SPI_CS0_N_INDEX]			= 21,  /*GPIO_SPI_CS0_N*/
	[GPIO_DISPLAY_RESET_INDEX]		= 90,  /*GPIO_DISPLAY_RESET*/
	[GPIO_DISPLAY_PWR_EN_INDEX]		= GPIO_INVALID,    /*GPIO_DISPLAY_PWR_EN*/
	[GPIO_LCDC_BRDG_PD_INDEX]		= 128, /*	GPIO_LCDC_BRDG_PD*/
	[GPIO_LCDC_BRDG_RESET_N_INDEX]	= 129, /*GPIO_LCDC_BRDG_RESET_N*/
	[GPIO_LCD_DSI_SEL_INDEX]		= 125, /*GPIO_LCD_DSI_SEL*/
	[MDP_303_VSYNC_GPIO_INDEX]		= 97,  /*MDP_303_VSYNC_GPIO*/
	[GPIO_LCDC_PCLK_INDEX]			= 4,   /*GPIO_LCDC_PCLK*/
	[LCD_CAMERA_LDO_2V8_INDEX]		= 35,  /*LCD_CAMERA_LDO_2V8*/
	[LCD_CAMERA_LDO_1V8_INDEX]		= 34,  /*LCD_CAMERA_LDO_1V8*/
};

unsigned int msm_lcd_gpio_table_qrd_7227a_sku3_1[LCD_GPIO_TOTAL_NUM] =
{
	[GPIO_BACKLIGHT_EN_INDEX]		= 89, /*GPIO_BACKLIGHT_EN*/
	[GPIO_SPI_MOSI_INDEX]			= 19,  /*GPIO_SPI_MOSI*/
	[GPIO_SPI_CLK_INDEX]			= 20,  /*GPIO_SPI_CLK*/
	[GPIO_SPI_CS0_N_INDEX]			= 21,  /*GPIO_SPI_CS0_N*/
	[GPIO_DISPLAY_RESET_INDEX]		= 90,  /*GPIO_DISPLAY_RESET*/
	[GPIO_DISPLAY_PWR_EN_INDEX]		= GPIO_INVALID,    /*GPIO_DISPLAY_PWR_EN*/
	[GPIO_LCDC_BRDG_PD_INDEX]		= 128, /*	GPIO_LCDC_BRDG_PD*/
	[GPIO_LCDC_BRDG_RESET_N_INDEX]	= 129, /*GPIO_LCDC_BRDG_RESET_N*/
	[GPIO_LCD_DSI_SEL_INDEX]		= 125, /*GPIO_LCD_DSI_SEL*/
	[MDP_303_VSYNC_GPIO_INDEX]		= 97,  /*MDP_303_VSYNC_GPIO*/
	[GPIO_LCDC_PCLK_INDEX]			= 4,   /*GPIO_LCDC_PCLK*/
	[LCD_CAMERA_LDO_2V8_INDEX]		= 35,  /*LCD_CAMERA_LDO_2V8*/
	[LCD_CAMERA_LDO_1V8_INDEX]		= 58,  /*LCD_CAMERA_LDO_1V8*/
};

